### ISSUE TITLE
Поиск резюме по тегам.

### ISSUE THREAD

**Issue by Vladislavlatfulin** [InfernumPegasus/lab2#2]
Добрый времени суток! Ожидается ли добавление поиска резюме других людей по тегам?

**Comment by InfernumPegasus** [comment]
Доброго времени суток! Нет. Наше приложение сохраняет резюме пользователей в их личном аккаунте, который закрыт для посторонних пользователей.

**Comment by Vladislavlatfulin** [comment]
Доброго времени суток! Ок.
